version: "3.1"
services:
  php:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      - services

  mysql:
    image: mysql:8
    restart: always
    #storing the mysql folder outside allows persistence
    #of databases between executions
    volumes:
      - ./docker/dock-mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - 3306:3306
    networks:
      - services

networks:
  services: