<?php

namespace eDreams\Tests\Integration;

use eDreams\Database\Factories\CapsuleFactory;
use PHPUnit\Framework\TestCase;

class AbstractTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $db = CapsuleFactory::get()->getDatabaseManager();
        $db->beginTransaction();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $db = CapsuleFactory::get()->getDatabaseManager();
        $db->rollBack();
    }
}
